enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  os: [darwin, linux, win32]
  cpu: [x64, arm64]

packageExtensions:
  "uWebSockets.js@*":
    dependencies:
      "node-gyp": "^9.0.0"

enableScripts: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
